export interface FullProject {
	slug: string;
	title: string;
	client: string;
	year: string;
	/** Primary category — used for the tag shown on the project page header. */
	category: string;
	/**
	 * Filter categories — used by the home pill filter (SelectedWork).
	 * A project can belong to multiple pills (e.g. a SaaS project also
	 * counts as UI/UX). If omitted, falls back to `[category]`.
	 */
	categories?: string[];
	shortDesc: string;
	fullDesc: string;
	thumbnail: string;
	gallery: string[];
	tags: string[];
	featured: boolean;
	orientation: 'portrait' | 'landscape';
}

// Sourced from ../portfolio-cms-v2.xlsx (Projects sheet). full_desc entries
// marked PLACEHOLDER in the sheet are early scaffolding text, not final copy.
export const allProjects: FullProject[] = [
	{
		slug: 'sonary-dashboard',
		title: `Sonary — Software Stack Manager`,
		client: `Ryze Beyond`,
		year: '2025',
		category: 'SaaS',
		categories: ['SaaS', 'UI/UX'],
		shortDesc: `Sole-designed a SaaS to track software subscriptions — full dark/light design system, 96+ shipped frames, AI-powered flows.`,
		fullDesc: `PLACEHOLDER : Case study complet Sonary Dashboard. Contexte : Ryze Beyond a lancé Sonary pour aider les équipes à tracker et optimiser leurs abonnements SaaS (comme Hubspot, Adobe, Zoom, GitHub). Rôle : Product designer solo, de la recherche utilisateur au shipping. Livrables : design system complet (dark + light mode), 6 features majeures (Software Stack, Calculators, User Settings, Login, Dashboard, AI Chat Bot), architecture responsive full-width Desktop 1920 + Laptop 1280 + Tablet 992 + Mobile 375, gestion des états (empty, loading, filters, multi-select, modals), 96+ frames livrées. Impact : produit clé dans la line Ryze Beyond, contribue au revenue growth.`,
		// Homepage thumb switched to the real Dashboard screen (the 4 gradient
		// stat cards + donut + spend timeline) — more recognizable than the
		// software-stack table for a first impression.
		thumbnail: 'https://res.cloudinary.com/akael/image/upload/v1785342119/portfolio/sonary-dashboard/07---dashboard/desktop/dark-mode/dashboard.webp',
		gallery: [
			// Featured first (David preference 2026-08-06): the 4-stat-cards
			// dashboard opens Desktop·Dark, the team-member-board opens
			// Desktop·Light — most recognizable frames for the case study.
			'https://res.cloudinary.com/akael/image/upload/v1785342119/portfolio/sonary-dashboard/07---dashboard/desktop/dark-mode/dashboard.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342098/portfolio/sonary-dashboard/05---user-setting/desktop/light-mode/team-member-board.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342017/portfolio/sonary-dashboard/01---software-stack-page/desktop/dark-mode/dashboard---grid-with-all-columns-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342019/portfolio/sonary-dashboard/01---software-stack-page/desktop/dark-mode/dashboard---grid-with-all-columns.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342020/portfolio/sonary-dashboard/01---software-stack-page/desktop/dark-mode/dashboard---list---bulk-selection-button-delete.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342022/portfolio/sonary-dashboard/01---software-stack-page/desktop/dark-mode/dashboard---list---categories-dropdown-open.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342023/portfolio/sonary-dashboard/01---software-stack-page/desktop/dark-mode/dashboard---list---popup-delete-software.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342024/portfolio/sonary-dashboard/01---software-stack-page/desktop/dark-mode/dashboard---list---status-dropdown-open.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342026/portfolio/sonary-dashboard/01---software-stack-page/desktop/dark-mode/dashboard---list-with-all-columns.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342028/portfolio/sonary-dashboard/01---software-stack-page/desktop/dark-mode/popups-set-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342029/portfolio/sonary-dashboard/01---software-stack-page/desktop/dark-mode/popups-set-2.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342031/portfolio/sonary-dashboard/01---software-stack-page/desktop/light-mode/dashboard---grid-with-all-columns.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342032/portfolio/sonary-dashboard/01---software-stack-page/desktop/light-mode/dashboard---list---categories-dropdown-open.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342034/portfolio/sonary-dashboard/01---software-stack-page/desktop/light-mode/dashboard---list---status-dropdown-open.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342035/portfolio/sonary-dashboard/01---software-stack-page/desktop/light-mode/dashboard---list-with-all-columns.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342036/portfolio/sonary-dashboard/01---software-stack-page/mobile/dark-mode/dashboard---empty---mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342038/portfolio/sonary-dashboard/01---software-stack-page/mobile/dark-mode/dashboard---grid---colapsed.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342039/portfolio/sonary-dashboard/01---software-stack-page/mobile/dark-mode/dashboard---grid---mobile---bottom-menu.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342040/portfolio/sonary-dashboard/01---software-stack-page/mobile/dark-mode/dashboard---grid---mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342042/portfolio/sonary-dashboard/01---software-stack-page/mobile/dark-mode/dashboard---grid---open-filter.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342043/portfolio/sonary-dashboard/01---software-stack-page/mobile/dark-mode/dashboard---list---mobile---bottom-menu.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342044/portfolio/sonary-dashboard/01---software-stack-page/mobile/dark-mode/dashboard---list---mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342046/portfolio/sonary-dashboard/01---software-stack-page/mobile/dark-mode/dashboard---list--open-filter.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342047/portfolio/sonary-dashboard/01---software-stack-page/mobile/dark-mode/lightbox-375.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342048/portfolio/sonary-dashboard/01---software-stack-page/mobile/dark-mode/question-in-2-steps.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342050/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/3-steps.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342051/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/dashboard---grid---mobile---bottom-menu.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342053/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/dashboard---grid---mobile-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342054/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/dashboard---grid---mobile-2.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342055/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/dashboard---grid---mobile-3.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342056/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/dashboard---grid---mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342057/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/dashboard---list---mobile---bottom-menu.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342059/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/dashboard---list---mobile-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342060/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/dashboard---list---mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342062/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/dropdown-375.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342063/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/edit-software-992.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342064/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/lightbox-375.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342066/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/popup-375.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342067/portfolio/sonary-dashboard/01---software-stack-page/mobile/light-mode/question-in-2-steps.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342068/portfolio/sonary-dashboard/03---calculators-main-page/desktop/dark-mode/dashboard---forms.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342070/portfolio/sonary-dashboard/03---calculators-main-page/desktop/light-mode/dashboard---forms.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342074/portfolio/sonary-dashboard/03---calculators-main-page/mobile/dark-mode/dashboard---forms.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342075/portfolio/sonary-dashboard/03---calculators-main-page/mobile/light-mode/dashboard---forms.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342078/portfolio/sonary-dashboard/05---user-setting/desktop/dark-mode/dashboard---list-with-all-columns.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342080/portfolio/sonary-dashboard/05---user-setting/desktop/dark-mode/profile-settings-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342081/portfolio/sonary-dashboard/05---user-setting/desktop/dark-mode/profile-settings.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342082/portfolio/sonary-dashboard/05---user-setting/desktop/dark-mode/reset-password---google---facebook---linkedin.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342083/portfolio/sonary-dashboard/05---user-setting/desktop/dark-mode/reset-password.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342085/portfolio/sonary-dashboard/05---user-setting/desktop/dark-mode/team-member-dropdown-menu---edit---resend---remove.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342086/portfolio/sonary-dashboard/05---user-setting/desktop/dark-mode/team-member-board-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342087/portfolio/sonary-dashboard/05---user-setting/desktop/dark-mode/team-member-board.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342089/portfolio/sonary-dashboard/05---user-setting/desktop/light-mode/dashboard---list-with-all-columns.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342090/portfolio/sonary-dashboard/05---user-setting/desktop/light-mode/profile-settings-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342091/portfolio/sonary-dashboard/05---user-setting/desktop/light-mode/profile-settings.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342093/portfolio/sonary-dashboard/05---user-setting/desktop/light-mode/reset-password---google---facebook---linkedin.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342094/portfolio/sonary-dashboard/05---user-setting/desktop/light-mode/reset-password.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342096/portfolio/sonary-dashboard/05---user-setting/desktop/light-mode/team-member-dropdown-menu---edit---resend---remove.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342097/portfolio/sonary-dashboard/05---user-setting/desktop/light-mode/team-member-board-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342099/portfolio/sonary-dashboard/05---user-setting/mobile/dark-mode/dashboard---list---mobile-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342101/portfolio/sonary-dashboard/05---user-setting/mobile/dark-mode/dashboard---list---mobile-2.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342102/portfolio/sonary-dashboard/05---user-setting/mobile/dark-mode/dashboard---list---mobile-3.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342103/portfolio/sonary-dashboard/05---user-setting/mobile/dark-mode/dashboard---list---mobile-4.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342104/portfolio/sonary-dashboard/05---user-setting/mobile/dark-mode/dashboard---list---mobile-5.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342106/portfolio/sonary-dashboard/05---user-setting/mobile/dark-mode/dashboard---list---mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342107/portfolio/sonary-dashboard/05---user-setting/mobile/dark-mode/reset-password.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342108/portfolio/sonary-dashboard/05---user-setting/mobile/light-mode/dashboard---list---mobile-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342109/portfolio/sonary-dashboard/05---user-setting/mobile/light-mode/dashboard---list---mobile-2.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342111/portfolio/sonary-dashboard/05---user-setting/mobile/light-mode/dashboard---list---mobile-3.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342112/portfolio/sonary-dashboard/05---user-setting/mobile/light-mode/dashboard---list---mobile-4.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342113/portfolio/sonary-dashboard/05---user-setting/mobile/light-mode/dashboard---list---mobile-5.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342114/portfolio/sonary-dashboard/05---user-setting/mobile/light-mode/dashboard---list---mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342116/portfolio/sonary-dashboard/05---user-setting/mobile/light-mode/reset-password.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342117/portfolio/sonary-dashboard/07---dashboard/desktop/dark-mode/dashboard-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342121/portfolio/sonary-dashboard/07---dashboard/mobile/dark-mode/dashboard.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342123/portfolio/sonary-dashboard/16---chat-bot/desktop/dark-mode/01.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342124/portfolio/sonary-dashboard/16---chat-bot/desktop/dark-mode/02.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342126/portfolio/sonary-dashboard/16---chat-bot/desktop/dark-mode/03.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342127/portfolio/sonary-dashboard/16---chat-bot/desktop/dark-mode/04.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342129/portfolio/sonary-dashboard/16---chat-bot/desktop/dark-mode/05.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342130/portfolio/sonary-dashboard/16---chat-bot/desktop/dark-mode/06.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342132/portfolio/sonary-dashboard/16---chat-bot/desktop/light-mode/01.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342133/portfolio/sonary-dashboard/16---chat-bot/desktop/light-mode/02.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342135/portfolio/sonary-dashboard/16---chat-bot/desktop/light-mode/03.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342136/portfolio/sonary-dashboard/16---chat-bot/desktop/light-mode/04.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342137/portfolio/sonary-dashboard/16---chat-bot/desktop/light-mode/05.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342139/portfolio/sonary-dashboard/16---chat-bot/desktop/light-mode/collapse.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342140/portfolio/sonary-dashboard/16---chat-bot/mobile/dark-mode/mobile---01.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342142/portfolio/sonary-dashboard/16---chat-bot/mobile/dark-mode/mobile---02.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342144/portfolio/sonary-dashboard/16---chat-bot/mobile/dark-mode/mobile---04.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342145/portfolio/sonary-dashboard/16---chat-bot/mobile/dark-mode/mobile---07.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342146/portfolio/sonary-dashboard/16---chat-bot/mobile/light-mode/mobile---10.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342147/portfolio/sonary-dashboard/16---chat-bot/mobile/light-mode/mobile---11.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342149/portfolio/sonary-dashboard/16---chat-bot/mobile/light-mode/mobile---14.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342150/portfolio/sonary-dashboard/16---chat-bot/mobile/light-mode/mobile---8.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342151/portfolio/sonary-dashboard/16---chat-bot/mobile/light-mode/mobile---9.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342473/portfolio/sonary-dashboard/16-chat-bot/mobile/dark-mode/mobile-03.webp',
		],
		tags: ['SaaS', 'Dashboard', 'Design System', 'Dark Mode', 'AI-UX', 'Responsive'],
		featured: true,
		orientation: 'landscape',
	},
	{
		slug: 'sonary-website',
		title: `Sonary — Marketing Website`,
		client: `Ryze Beyond`,
		year: '2025',
		category: 'SaaS',
		categories: ['SaaS', 'UI/UX'],
		shortDesc: `Marketing site with review hub, comparison pages and content architecture — designed for SEO scale from day one.`,
		fullDesc: `PLACEHOLDER : Design du site marketing Sonary. Sections : Homepage, Review Hub, Review Page, Article Hub, Articles, Lineup, Alternative Prod Info, Write a Review, Legal. Approche : storytelling produit + SEO-optimized, structure content-heavy scalable.`,
		thumbnail: 'https://res.cloudinary.com/akael/image/upload/v1785342169/portfolio/sonary-website/alternative-prod-info/alternative---desktop.webp',
		gallery: [
			'https://res.cloudinary.com/akael/image/upload/v1785342169/portfolio/sonary-website/alternative-prod-info/alternative---desktop.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342172/portfolio/sonary-website/alternative-prod-info/mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342174/portfolio/sonary-website/article-hub/article-hub-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342177/portfolio/sonary-website/article-hub/article-hub.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342180/portfolio/sonary-website/articles/article---desktop.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342183/portfolio/sonary-website/articles/article---mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342185/portfolio/sonary-website/homepage/home-page-desktop.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342187/portfolio/sonary-website/homepage/home-page-mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342190/portfolio/sonary-website/legal/legal-page---desktop.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342193/portfolio/sonary-website/lineup/lineup---desktop.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342195/portfolio/sonary-website/lineup/lineup---mobile-1.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342197/portfolio/sonary-website/lineup/lineup---mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342199/portfolio/sonary-website/review-hub/desktop.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342201/portfolio/sonary-website/review-hub/mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342204/portfolio/sonary-website/review-page/review-page---desktop-side-table-of-content.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342207/portfolio/sonary-website/review-page/review-page---with-table-of-content-open---mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342208/portfolio/sonary-website/write-a-review/write-review-step-2---desktop.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342210/portfolio/sonary-website/write-a-review/write-review-step-2---mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342476/portfolio/sonary-website/legal/legal-page-mobile.webp',
		],
		tags: ['SaaS', 'Marketing Site', 'Content', 'SEO'],
		featured: true,
		orientation: 'portrait',
	},
	{
		slug: 'sonary-mailer',
		title: `Sonary — Email Templates`,
		client: `Ryze Beyond`,
		year: '2025',
		category: 'SaaS',
		categories: ['SaaS', 'UI/UX'],
		shortDesc: `Full email system — 4 mailer templates × responsive, dark-mode aware, on-brand across the funnel.`,
		fullDesc: `PLACEHOLDER : Design de la suite email Sonary. 4 mailers Desktop + 4 Mobile. Focus : cohérence design system, lisibilité, dark mode support, CTAs clairs.`,
		thumbnail: 'https://res.cloudinary.com/akael/image/upload/v1785342153/portfolio/sonary-mailer/desktop/mailer-1-desktop.webp',
		gallery: [
			'https://res.cloudinary.com/akael/image/upload/v1785342153/portfolio/sonary-mailer/desktop/mailer-1-desktop.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342154/portfolio/sonary-mailer/desktop/mailer-2-desktop.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342156/portfolio/sonary-mailer/desktop/mailer-3-desktop.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342157/portfolio/sonary-mailer/desktop/mailer-4-desktop.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342159/portfolio/sonary-mailer/mobile/mailer-1-mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342160/portfolio/sonary-mailer/mobile/mailer-2-mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342161/portfolio/sonary-mailer/mobile/mailer-3-mobile.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342163/portfolio/sonary-mailer/mobile/mailer-4-mobile.webp',
		],
		tags: ['Email Design', 'Templates', 'Responsive'],
		featured: false,
		orientation: 'landscape',
	},
	{
		slug: 'playright',
		title: `Playright`,
		client: `Ryze Beyond`,
		year: '2024',
		category: 'SaaS',
		categories: ['SaaS', 'UI/UX'],
		shortDesc: `Homepage and product list for Playright — focused on conversion and product clarity.`,
		fullDesc: `PLACEHOLDER : Design de Playright. Focus sur la conversion et la présentation produit.`,
		thumbnail: 'https://res.cloudinary.com/akael/image/upload/v1785341989/portfolio/playright/home-page/desktop---1200px---container-1140px.webp',
		gallery: [
			'https://res.cloudinary.com/akael/image/upload/v1785341989/portfolio/playright/home-page/desktop---1200px---container-1140px.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785341991/portfolio/playright/home-page/desktop---1920px---container-1140px.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785341993/portfolio/playright/home-page/laptop---992px---container-944px.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785341995/portfolio/playright/home-page/mobile---375px---container-343px.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785341997/portfolio/playright/home-page/tablet---768px---container-720px.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342000/portfolio/playright/prodlist/mobile---375px---container-343px.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342002/portfolio/playright/prodlist/tablet---768px---container-720px.webp',
		],
		tags: ['SaaS', 'Product Page', 'UX'],
		featured: false,
		orientation: 'portrait',
	},
	{
		slug: 'top5',
		title: `Top5`,
		client: `Ryze Beyond`,
		year: '2024',
		category: 'SaaS',
		categories: ['SaaS', 'UI/UX'],
		shortDesc: `Editorial comparison system — article, comparison and lineup pages built for premium content at scale.`,
		fullDesc: `PLACEHOLDER : Design Top5 : Article, Comparison, Lineup pages. Approche éditoriale premium pour aider les users à comparer produits/services.`,
		thumbnail: 'https://res.cloudinary.com/akael/image/upload/v1785342213/portfolio/top5/article/article-side-bar-1920.webp',
		gallery: [
			'https://res.cloudinary.com/akael/image/upload/v1785342213/portfolio/top5/article/article-side-bar-1920.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342215/portfolio/top5/article/article-375.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342217/portfolio/top5/comparison/comparison-page---desktop-1920.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342219/portfolio/top5/comparison/mobile---375---inner-343.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342222/portfolio/top5/lineup/website-width-1920---container-1140---lineup-950.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342225/portfolio/top5/lineup/website-width-375---container-343---lineup-344.webp',
		],
		tags: ['SaaS', 'Editorial', 'Comparison'],
		featured: false,
		orientation: 'portrait',
	},
	{
		slug: 'ryze-hub',
		title: `Ryze Beyond Hub`,
		client: `Ryze Beyond`,
		year: '2024',
		category: 'UI/UX',
		shortDesc: `Company hub and portfolio landing — a single surface tying Ryze Beyond's product line together.`,
		fullDesc: `PLACEHOLDER : Design du hub Ryze Beyond, présentation portfolio produits + landing pages Desktop et Mobile.`,
		thumbnail: 'https://res.cloudinary.com/akael/image/upload/v1785342009/portfolio/ryze-hub/desktop/company-hub---home-page---step-01.webp',
		gallery: [
			'https://res.cloudinary.com/akael/image/upload/v1785342009/portfolio/ryze-hub/desktop/company-hub---home-page---step-01.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342011/portfolio/ryze-hub/desktop/company-hub---home-page---step-02.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342012/portfolio/ryze-hub/desktop/company-hub---home-page---step-03.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342014/portfolio/ryze-hub/desktop/company-hub---innerpage---step-04.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342016/portfolio/ryze-hub/mobile/company-hub---innerpage---step-04.webp',
		],
		tags: ['Branding', 'Landing', 'Corporate'],
		featured: false,
		orientation: 'portrait',
	},
	{
		slug: 'ryze-brand',
		title: `Ryze Beyond — Brand`,
		client: `Ryze Beyond`,
		year: '2024',
		category: 'UI/UX',
		shortDesc: `Visual identity system for Ryze Beyond — logo, palette, motion and web-facing brand elements.`,
		fullDesc: `PLACEHOLDER : Éléments d'identité de marque pour Ryze Beyond.`,
		thumbnail: 'https://res.cloudinary.com/akael/image/upload/v1785342005/portfolio/ryze/ryze-website---homepage---example-of-lines-per-section.webp',
		gallery: [
			'https://res.cloudinary.com/akael/image/upload/v1785342005/portfolio/ryze/ryze-website---homepage---example-of-lines-per-section.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785342007/portfolio/ryze/ryze-website---homepage---mobile.webp',
		],
		tags: ['Branding', 'Identity'],
		featured: false,
		orientation: 'portrait',
	},
	{
		slug: 'casino-work',
		title: `10Bet & Casino Gaming Suite`,
		client: `Gamingtech / Tradologic`,
		year: '2016',
		category: 'Gaming',
		shortDesc: `20+ casino UI screens (2011–2017) — game lobbies, bonus systems, deposit funnels, mobile-first.`,
		fullDesc: `PLACEHOLDER : Design de plateformes casino online sur plusieurs années (Gamingtech 2015-2017 pour 10Bet, Real Deal Bet, Bet Rally + Tradologic 2011-2013). Livrables : lobbies de jeux, systèmes de bonus, tunnels de dépôt, interfaces mobile/desktop, animations HTML5/CSS3.`,
		thumbnail: 'https://res.cloudinary.com/akael/image/upload/v1785345974/portfolio/old-wix/casino/casino-01.webp',
		gallery: [
			'https://res.cloudinary.com/akael/image/upload/v1785345974/portfolio/old-wix/casino/casino-01.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345976/portfolio/old-wix/casino/casino-02.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345978/portfolio/old-wix/casino/casino-03.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345979/portfolio/old-wix/casino/casino-04.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345981/portfolio/old-wix/casino/casino-05.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345982/portfolio/old-wix/casino/casino-06.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345984/portfolio/old-wix/casino/casino-07.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345986/portfolio/old-wix/casino/casino-08.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345988/portfolio/old-wix/casino/casino-09.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345989/portfolio/old-wix/casino/casino-10.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345991/portfolio/old-wix/casino/casino-11.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345993/portfolio/old-wix/casino/casino-12.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345994/portfolio/old-wix/casino/casino-13.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345996/portfolio/old-wix/casino/casino-14.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345998/portfolio/old-wix/casino/casino-15.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346000/portfolio/old-wix/casino/casino-16.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346001/portfolio/old-wix/casino/casino-17.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346002/portfolio/old-wix/casino/casino-18.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346004/portfolio/old-wix/casino/casino-19.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346006/portfolio/old-wix/casino/casino-20.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346008/portfolio/old-wix/casino/casino-21.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346010/portfolio/old-wix/casino/casino-22.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346012/portfolio/old-wix/casino/casino-23.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346013/portfolio/old-wix/casino/casino-24.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346015/portfolio/old-wix/casino/casino-25.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346016/portfolio/old-wix/casino/casino-26.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346018/portfolio/old-wix/casino/casino-27.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346020/portfolio/old-wix/casino/casino-28.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346021/portfolio/old-wix/casino/casino-29.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346023/portfolio/old-wix/casino/casino-30.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346025/portfolio/old-wix/casino/casino-31.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346026/portfolio/old-wix/casino/casino-32.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346028/portfolio/old-wix/casino/casino-33.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346029/portfolio/old-wix/casino/casino-34.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346031/portfolio/old-wix/casino/casino-35.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346033/portfolio/old-wix/casino/casino-36.webp',
		],
		tags: ['Gaming', 'Casino', 'Mobile', 'HTML5', 'Animation'],
		featured: false,
		orientation: 'portrait',
	},
	{
		slug: 'sport-betting',
		title: `Sport Betting Platforms`,
		client: `Gamingtech`,
		year: '2016',
		category: 'Gaming',
		shortDesc: `Live sport-betting interfaces for 10Bet and Real Deal Bet — real-time odds tables, HTML5 animations.`,
		fullDesc: `PLACEHOLDER : Design de plateformes sport betting online chez Gamingtech (2015-2017). Livrables : interfaces de paris live, calendriers interactifs, tableaux de cotes, animations HTML5.`,
		thumbnail: 'https://res.cloudinary.com/akael/image/upload/v1785346043/portfolio/old-wix/sport-betting/sport-betting-01.webp',
		gallery: [
			'https://res.cloudinary.com/akael/image/upload/v1785346043/portfolio/old-wix/sport-betting/sport-betting-01.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346045/portfolio/old-wix/sport-betting/sport-betting-02.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346047/portfolio/old-wix/sport-betting/sport-betting-03.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346049/portfolio/old-wix/sport-betting/sport-betting-04.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346051/portfolio/old-wix/sport-betting/sport-betting-05.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346052/portfolio/old-wix/sport-betting/sport-betting-06.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346054/portfolio/old-wix/sport-betting/sport-betting-07.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346055/portfolio/old-wix/sport-betting/sport-betting-08.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346057/portfolio/old-wix/sport-betting/sport-betting-09.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346059/portfolio/old-wix/sport-betting/sport-betting-10.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346060/portfolio/old-wix/sport-betting/sport-betting-11.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346062/portfolio/old-wix/sport-betting/sport-betting-12.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346064/portfolio/old-wix/sport-betting/sport-betting-13.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346066/portfolio/old-wix/sport-betting/sport-betting-14.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346068/portfolio/old-wix/sport-betting/sport-betting-15.webp',
		],
		tags: ['Gaming', 'Sport Betting', 'Live'],
		featured: false,
		orientation: 'portrait',
	},
	{
		slug: 'branding-old',
		title: `Branding & Identity Work (2006-2015)`,
		client: `Arc Interactive / Publicis`,
		year: '2010',
		category: 'Branding',
		shortDesc: `13 brand identities from the Arc Interactive / Publicis years (2006–2011) — same period as the Cactus wins.`,
		fullDesc: `PLACEHOLDER : Sélection de travaux branding réalisés chez Arc Interactive (Publicis Group), 2006-2011, période récompensée par Cactus d'Or/Argent/Bronze. Logos, palettes, guidelines, campaigns.`,
		thumbnail: 'https://res.cloudinary.com/akael/image/upload/v1785345947/portfolio/old-wix/branding/branding-01.webp',
		gallery: [
			'https://res.cloudinary.com/akael/image/upload/v1785345947/portfolio/old-wix/branding/branding-01.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345949/portfolio/old-wix/branding/branding-02.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345953/portfolio/old-wix/branding/branding-03.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345954/portfolio/old-wix/branding/branding-04.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345956/portfolio/old-wix/branding/branding-05.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345959/portfolio/old-wix/branding/branding-06.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345962/portfolio/old-wix/branding/branding-07.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345964/portfolio/old-wix/branding/branding-08.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345966/portfolio/old-wix/branding/branding-09.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345968/portfolio/old-wix/branding/branding-10.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345970/portfolio/old-wix/branding/branding-11.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345971/portfolio/old-wix/branding/branding-12.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785345973/portfolio/old-wix/branding/branding-13.webp',
		],
		tags: ['Branding', 'Identity', 'Publicis', 'Awarded'],
		featured: false,
		orientation: 'portrait',
	},
	{
		slug: 'ui-ux-vintage',
		title: `UI/UX Work (2011-2018)`,
		client: `Multiple clients`,
		year: '2015',
		category: 'UI/UX',
		shortDesc: `20 selected UI/UX screens from earlier years — fintech, mobile apps, dashboards (Smart.bid, Wochat and others).`,
		fullDesc: `PLACEHOLDER : Sélection de projets UI/UX antérieurs à Ryze Beyond. Fintech (Smart.bid/LoanMax 2018-2019), Wochat mobile app 2017-2018, autres missions.`,
		thumbnail: 'https://res.cloudinary.com/akael/image/upload/v1785346069/portfolio/old-wix/ui-ux/ui-ux-01.webp',
		gallery: [
			'https://res.cloudinary.com/akael/image/upload/v1785346069/portfolio/old-wix/ui-ux/ui-ux-01.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346071/portfolio/old-wix/ui-ux/ui-ux-02.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346073/portfolio/old-wix/ui-ux/ui-ux-03.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346075/portfolio/old-wix/ui-ux/ui-ux-04.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346076/portfolio/old-wix/ui-ux/ui-ux-05.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346078/portfolio/old-wix/ui-ux/ui-ux-06.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346080/portfolio/old-wix/ui-ux/ui-ux-07.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346081/portfolio/old-wix/ui-ux/ui-ux-08.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346083/portfolio/old-wix/ui-ux/ui-ux-09.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346084/portfolio/old-wix/ui-ux/ui-ux-10.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346086/portfolio/old-wix/ui-ux/ui-ux-11.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346088/portfolio/old-wix/ui-ux/ui-ux-12.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346089/portfolio/old-wix/ui-ux/ui-ux-13.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346092/portfolio/old-wix/ui-ux/ui-ux-14.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346094/portfolio/old-wix/ui-ux/ui-ux-15.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346096/portfolio/old-wix/ui-ux/ui-ux-16.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346098/portfolio/old-wix/ui-ux/ui-ux-17.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346099/portfolio/old-wix/ui-ux/ui-ux-18.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346101/portfolio/old-wix/ui-ux/ui-ux-19.webp',
			'https://res.cloudinary.com/akael/image/upload/v1785346103/portfolio/old-wix/ui-ux/ui-ux-20.webp',
		],
		tags: ['UI', 'UX', 'Fintech', 'Mobile'],
		featured: false,
		orientation: 'portrait',
	},
];
