export interface CraftItem {
	slug: string;
	title: string;
	year: string;
	category: string;
	description: string;
	image: string;
	tags: string[];
}

// Sourced from ../portfolio-cms-v2.xlsx (Craft sheet). Descriptions marked
// PLACEHOLDER are early scaffolding text, not final copy.
export const craftItems: CraftItem[] = [
	{
		slug: '3d-01',
		title: `3D artwork #1`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345908/portfolio/old-wix/3d/3d-01.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-02',
		title: `3D artwork #2`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345909/portfolio/old-wix/3d/3d-02.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-03',
		title: `3D artwork #3`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345911/portfolio/old-wix/3d/3d-03.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-04',
		title: `3D artwork #4`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345912/portfolio/old-wix/3d/3d-04.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-05',
		title: `3D artwork #5`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345914/portfolio/old-wix/3d/3d-05.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-06',
		title: `3D artwork #6`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345916/portfolio/old-wix/3d/3d-06.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-07',
		title: `3D artwork #7`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345917/portfolio/old-wix/3d/3d-07.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-08',
		title: `3D artwork #8`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345919/portfolio/old-wix/3d/3d-08.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-09',
		title: `3D artwork #9`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345920/portfolio/old-wix/3d/3d-09.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-10',
		title: `3D artwork #10`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345921/portfolio/old-wix/3d/3d-10.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-11',
		title: `3D artwork #11`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345923/portfolio/old-wix/3d/3d-11.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-12',
		title: `3D artwork #12`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345924/portfolio/old-wix/3d/3d-12.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-13',
		title: `3D artwork #13`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345926/portfolio/old-wix/3d/3d-13.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-14',
		title: `3D artwork #14`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345928/portfolio/old-wix/3d/3d-14.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-15',
		title: `3D artwork #15`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345929/portfolio/old-wix/3d/3d-15.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-16',
		title: `3D artwork #16`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345931/portfolio/old-wix/3d/3d-16.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-17',
		title: `3D artwork #17`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345932/portfolio/old-wix/3d/3d-17.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-18',
		title: `3D artwork #18`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345933/portfolio/old-wix/3d/3d-18.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-19',
		title: `3D artwork #19`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345935/portfolio/old-wix/3d/3d-19.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-20',
		title: `3D artwork #20`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345937/portfolio/old-wix/3d/3d-20.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-21',
		title: `3D artwork #21`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345938/portfolio/old-wix/3d/3d-21.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-22',
		title: `3D artwork #22`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345939/portfolio/old-wix/3d/3d-22.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-23',
		title: `3D artwork #23`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345941/portfolio/old-wix/3d/3d-23.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-24',
		title: `3D artwork #24`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345943/portfolio/old-wix/3d/3d-24.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: '3d-25',
		title: `3D artwork #25`,
		year: '2014',
		category: '3D',
		description: `PLACEHOLDER : rendu 3D personnel (ZBrush + Cinema 4D).`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785345944/portfolio/old-wix/3d/3d-25.webp',
		tags: ['3D', 'ZBrush', 'Cinema 4D'],
	},
	{
		slug: 'paint-01',
		title: `Digital painting #1`,
		year: '2013',
		category: 'Digital Painting',
		description: `PLACEHOLDER : peinture digitale exploratoire.`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785346035/portfolio/old-wix/digital-painting/digital-painting-01.webp',
		tags: ['Digital Art', 'Painting'],
	},
	{
		slug: 'paint-02',
		title: `Digital painting #2`,
		year: '2013',
		category: 'Digital Painting',
		description: `PLACEHOLDER : peinture digitale exploratoire.`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785346036/portfolio/old-wix/digital-painting/digital-painting-02.webp',
		tags: ['Digital Art', 'Painting'],
	},
	{
		slug: 'paint-03',
		title: `Digital painting #3`,
		year: '2013',
		category: 'Digital Painting',
		description: `PLACEHOLDER : peinture digitale exploratoire.`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785346037/portfolio/old-wix/digital-painting/digital-painting-03.webp',
		tags: ['Digital Art', 'Painting'],
	},
	{
		slug: 'paint-04',
		title: `Digital painting #4`,
		year: '2013',
		category: 'Digital Painting',
		description: `PLACEHOLDER : peinture digitale exploratoire.`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785346039/portfolio/old-wix/digital-painting/digital-painting-04.webp',
		tags: ['Digital Art', 'Painting'],
	},
	{
		slug: 'paint-05',
		title: `Digital painting #5`,
		year: '2013',
		category: 'Digital Painting',
		description: `PLACEHOLDER : peinture digitale exploratoire.`,
		image: 'https://res.cloudinary.com/akael/image/upload/v1785346040/portfolio/old-wix/digital-painting/digital-painting-05.webp',
		tags: ['Digital Art', 'Painting'],
	},
];
